image: openjdk:11
pipelines:
  default:
  - step:
      caches:
      - gradle
      script:
        - bash ./gradlew build
        - bash ./gradlew sonarqube -Dsonar.projectKey=tangly-os-at-tangly.net -Dsonar.organization=tangly-os -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN