image: openjdk:13
pipelines:
  default:
  - step:
      caches:
      - gradle
      - gradlewrapper
      script:
      - ./gradlew build jacocoMergeTests
      - ./gradlew sonarqube -Dsonar.projectKey=tangly-os-at-tangly.net -Dsonar.organization=tangly-os -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper