[versions]
junit-version = '5.8.0-M1'
jackson-version = '2.12.3'
microstream-version = '04.01.00-MS-GA'

[libraries]
annotations = "org.jetbrains:annotations:20.1.0"
apache-commons-cvs = "org.apache.commons:commons-csv:1.8"
arch-unit = "com.tngtech.archunit:archunit-junit5-api:0.18.0"
asciidoctorj-core = "org.asciidoctor:asciidoctorj:2.5.0"
asciidoctorj-pdf = "org.asciidoctor:asciidoctorj-pdf:1.5.4"
assertj = "org.assertj:assertj-core:3.18.1"
flyway = "org.flywaydb:flyway-core:7.8.2"
guice = "com.google.inject:guice:5.0.1"
hsqldb = "org.hsqldb:hsqldb:2.6.0"
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-parameters = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson-version" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-version" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-version" }
json-validator = "com.networknt:json-schema-validator:1.0.52"
json-core = "com.guicedee.services:json:1.0.19.13"
jimfs = "com.google.jimfs:jimfs:1.2"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-version" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-version" }
slf4j-api = "org.slf4j:slf4j-api:2.0.0-alpha1"
slf4j-logback = "ch.qos.logback:logback-core:1.3.0-alpha5"
microstream-storage = { module = "one.microstream:storage.embedded", version.ref = "microstream-version" }
microstream-config = { module = "one.microstream:storage.embedded.configuration", version.ref = "microstream-version" }
mockito = "org.mockito:mockito-junit-jupiter:3.9.0"
pdfbox = "org.apache.pdfbox:pdfbox:2.0.23"
socharts = "com.storedobject.chart:so-charts:2.1.0"
vaadin = "com.vaadin:vaadin-bom:19.0.6"

[bundles]
test-deps = ["junit-api", "assertj", "mockito", "arch-unit"]
jackson-deps = ["jackson-databind", "jackson-parameters", "jackson-datatype", "jackson-jsr310"]
