[versions]
jackson-version = '2.12.3'
jetty-version = '9.4.38.v20210224'
junit-version = '5.8.0-M1'
microstream-version = '04.01.00-MS-GA'
mustang-version = '2.1.1'
slf4j-version = '2.0.0-alpha1'

[libraries]
annotations = "org.jetbrains:annotations:20.1.0"
antrlr-st4 = "org.antlr:ST4:4.3.1"
apache-commons-csv = "org.apache.commons:commons-csv:1.8"
apache-commons-codec = "commons-codec:commons-codec:1.15"
apache-commons-io = "commons-io:commons-io:2.8.0"
apache-pdfbox = "org.apache.pdfbox:pdfbox:2.0.23"
arch-unit = "com.tngtech.archunit:archunit-junit5-api:0.18.0"
asciidoctorj-core = "org.asciidoctor:asciidoctorj:2.5.1"
asciidoctorj-pdf = "org.asciidoctor:asciidoctorj-pdf:1.5.4"
assertj = "org.assertj:assertj-core:3.18.1"
flyway = "org.flywaydb:flyway-core:7.8.2"
guice = "com.google.inject:guice:5.0.1"
hsqldb = "org.hsqldb:hsqldb:2.6.0"
ical4j-core  = "org.mnode.ical4j:ical4j:3.0.19"
ical4j-vcard = "org.mnode.ical4j:ical4j-vcard:1.0.5"
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jackson-parameters = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson-version" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-version" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-version" }
jakarta-mail = "com.sun.mail:jakarta.mail:2.0.1"
jimfs = "com.google.jimfs:jimfs:1.2"
mustang-core = { module = "org.mustangproject:library", version.ref = "mustang-version" }
mustang-validator = { module = "org.mustangproject:validator", version.ref = "mustang-version" }
qrbill = "net.codecrete.qrbill:qrbill-generator:2.5.2"

#Java 9 module compliant version of https://github.com/stleary/JSON-java
json-core = "com.guicedee.services:json:1.0.19.13"
json-validator = "com.networknt:json-schema-validator:1.0.52"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-version" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-version" }
google-libphonenumber = "com.googlecode.libphonenumber:libphonenumber:8.12.22"
iban4j = "org.iban4j:iban4j:3.2.2-RELEASE"
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-version" }
slf4j-logback = "ch.qos.logback:logback-core:1.3.0-alpha5"
microstream-storage = { module = "one.microstream:storage.embedded", version.ref = "microstream-version" }
microstream-config = { module = "one.microstream:storage.embedded.configuration", version.ref = "microstream-version" }
mockito = "org.mockito:mockito-junit-jupiter:3.9.0"

vaadin-core = "com.vaadin:vaadin-bom:19.0.6"
vaadin-autocomplete = "com.vaadin.componentfactory:autocomplete:2.3.1"
vaadin-pdfbrowser = "org.vaadin.alejandro:pdf-browser:3.1.0"
vaadin-socharts = "com.storedobject.chart:so-charts:2.1.0"
vaadin-tooltip = "com.vaadin.componentfactory:tooltip:1.3.5"
vaadin-signature = "de.f0rce.signaturepad:signature-widget:2.0.0"
vaadin-test = "com.github.mvysny.kaributesting:karibu-testing-v10:1.2.12"

jetty-continuation = { module = "org.eclipse.jetty:jetty-continuation", version.ref = "jetty-version" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty-version" }
jetty-websocket = { module = "org.eclipse.jetty.websocket:websocket-server", version.ref = "jetty-version" }
jetty-containers = "org.glassfish.jersey.containers:jersey-container-servlet:3.0.1"
jetty-websocketimp = { module = "org.eclipse.jetty.websocket:javax-websocket-server-impl", version.ref = "jetty-version" }

[bundles]
test-deps = ["junit-api", "assertj", "mockito", "arch-unit"]
jackson-deps = ["jackson-databind", "jackson-parameters", "jackson-datatype", "jackson-jsr310"]
jetty-deps = ["jetty-continuation", "jetty-server", "jetty-websocket", "jetty-containers"]
